#!/usr/bin/bash
# Fail is any init script fails
set -e

for f in $(find /docker-entrypoint-init.d/ -type f -name  '*.sh' | sort); do
    echo "Executing $f..."
    bash "$f"
done

# This needs to be last for systemd to become PID1
exec /usr/lib/systemd/systemd
