name: Acceptance Tests Coordinator

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**.java'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  determine_tests:
    runs-on: ubuntu-latest
    name: Determine Acceptance Tests to run
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i ioredis
      - id: changed_files
        uses: Ana06/get-changed-files@v2.3.0
        with:
          filter: '*.java'
      - id: tests_covering_pr
        name: Tests covering PR
        env:
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
        run: |
          recommended_tests=$(node .github/scripts/test_covering_pr.js ${{ steps.changed_files.outputs.added_modified }})
          echo "recommended_tests=$recommended_tests" >> $GITHUB_OUTPUT
          echo "Recommended Tests: $recommended_tests"
      - name: Determine if the acceptance tests should run
        id: determine_run_acceptance_tests
        run: |
          recommended_count=$(echo "${{ steps.tests_covering_pr.outputs.recommended_tests }}" | awk -F, '{print NF}' RS=)
          if [[ "$recommended_count" -gt 30 || "$recommended_count" -eq 0 ]]; then
            echo "run_acceptance_tests=true" >> $GITHUB_OUTPUT
          else
            echo "run_acceptance_tests=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      recommended_tests: ${{ steps.tests_covering_pr.outputs.recommended_tests }}
      run_acceptance_tests: ${{ steps.determine_run_acceptance_tests.outputs.run_acceptance_tests }}
      recommended_count: ${{ steps.determine_run_secondary.outputs.recommended_count }}

  trigger_recommended:
    needs: determine_tests
    uses: ./.github/workflows/recommended_tests.yml
    secrets: inherit  # VERY IMPORTANT: Pass secrets to the called workflow.

  run_recommended_tests:
    needs: trigger_recommended
    if: ${{ needs.trigger_recommended.outputs.run_acceptance_tests == 'false' }}
    uses: ./.github/workflows/acceptance_tests_base.yml
    with:
      tests: "19_run_recommended_tests.sh"
      server_id: "secondary_f"
      recommended_tests: ${{ needs.trigger_recommended.outputs.recommended_tests }}

  run_acceptance_tests:
    needs: trigger_recommended
    if: ${{ needs.trigger_recommended.outputs.run_acceptance_tests == 'true' }}
    uses: ./.github/workflows/acceptance_tests_sequential.yml
    with:
      run_acceptance_tests: ${{ needs.trigger_recommended.outputs.run_acceptance_tests }}

  run_additional_tests:
    needs: trigger_recommended
    if: ${{ needs.trigger_recommended.outputs.run_acceptance_tests == 'true' }}
    uses: ./.github/workflows/acceptance_tests_parallel.yml
    with:
      run_acceptance_tests: ${{ needs.trigger_recommended.outputs.run_acceptance_tests }}

  skip_recommended_tests:
    name: Skip Recommended Tests
    needs: trigger_recommended
    if: ${{ needs.trigger_recommended.outputs.run_acceptance_tests == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping recommended tests, running full suite."

  skip_acceptance_tests:
    name: Skip Acceptance and Additional Tests
    needs: trigger_recommended
    if: ${{ needs.trigger_recommended.outputs.run_acceptance_tests == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping acceptance and additional tests, running recommended tests."