name: acceptance-tests-fast
on:
  pull_request_target:
    types: [synchronize, opened, reopened]

jobs:
  wait-for-suggested-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for "Suggested tests to cover this Pull Request" to Complete
        run: |
          CHECK_NAME="Suggested tests to cover this Pull Request"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"

          echo "Waiting for '$CHECK_NAME' to complete..."

          while true; do
            # Fetch the latest check runs from the PR's HEAD commit
            CHECK_RUNS=$(gh api "repos/$REPO/actions/runs" --jq ".workflow_runs[] | select(.name == \"$CHECK_NAME\") | .status, .conclusion")

            if [[ -z "$CHECK_RUNS" ]]; then
              echo "⚠️  No check run found for '$CHECK_NAME' yet. Retrying..."
              sleep 10
              continue
            fi

            STATUS=$(echo "$CHECK_RUNS" | head -n1)
            CONCLUSION=$(echo "$CHECK_RUNS" | tail -n1)

            echo "Found check run: status=$STATUS, conclusion=$CONCLUSION"

            if [[ "$STATUS" == "completed" ]]; then
              if [[ "$CONCLUSION" == "success" ]]; then
                echo "✅ '$CHECK_NAME' completed successfully. Proceeding..."
                exit 0
              else
                echo "❌ '$CHECK_NAME' failed or was cancelled. Exiting..."
                exit 1
              fi
            fi

            echo "⏳ '$CHECK_NAME' is still running... waiting 10s"
            sleep 10
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  acceptance-tests-fast:
    needs: wait-for-suggested-tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Recommended Tests from PR Comment
        id: fetch-tests
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"
          
          TESTS=$(gh pr view $PR_NUMBER --repo $REPO --json comments --jq '.comments[] | select(.body | contains("<!-- suggested_tests -->")) | .body' | tail -n +2)
          echo "Recommended tests:"
          echo "$TESTS"
          echo "RECOMMENDED_TESTS=$TESTS" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Acceptance Tests
        uses: "./.github/workflows/acceptance_tests_common.yml"
        with:
          secondary_tests: "19_run_secondary_fast.sh"
          server_id: "secondary_f"
          recommended_tests: ${{ env.RECOMMENDED_TESTS }}
