name: "PR labeler trigger"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Labeler trigger workflow completed"
