name: Recommended Tests

on:
  pull_request_target:
    paths:
      - '**.java'

jobs:
  generate_recommended_tests:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pull Request code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i ioredis
      - id: changed_files
        uses: Ana06/get-changed-files@v2.3.0
        with:
          filter: '*.java'
      - id: tests_covering_pr
        name: Tests covering PR
        env:
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
        run: |
          recommended_tests=$(node .github/scripts/test_covering_pr.js ${{ steps.changed_files.outputs.added_modified }})
          echo "recommended_tests=$recommended_tests" >> $GITHUB_OUTPUT
          echo "Recommended Tests: $recommended_tests"
      - name: Determine if the acceptance tests should run
        id: determine_run_acceptance_tests
        run: |
          recommended_count=$(echo "${{ steps.tests_covering_pr.outputs.recommended_tests }}" | tr ',' '\n' | jq -s length)
          if [[ "$recommended_count" -gt 30 || "$recommended_count" -eq 0 ]]; then
            echo "run_acceptance_tests=true" >> $GITHUB_OUTPUT
          else
            echo "run_acceptance_tests=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      recommended_tests: ${{ steps.tests_covering_pr.outputs.recommended_tests }}
      run_acceptance_tests: ${{ steps.determine_run_acceptance_tests.outputs.run_acceptance_tests }}

  run_recommended_tests:
    name: Recommended tests
    needs: generate_recommended_tests
    # Only run if the full acceptance tests are skipped
    if: ${{ needs.generate_recommended_tests.outputs.run_acceptance_tests == 'false' }}
    uses: ./.github/workflows/acceptance_tests_base.yml
    with:
      tests: "19_run_recommended_tests.sh"
      server_id: "secondary_f"
      recommended_tests: ${{ needs.generate_recommended_tests.outputs.recommended_tests }}

  dummy_acceptance_tests:
    name: Dummy Acceptance tests status
    needs: generate_recommended_tests
    if: ${{ needs.generate_recommended_tests.outputs.run_acceptance_tests == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dummy Acceptance tests passed (skipped)"

  dummy_additional_tests:
    name: Dummy Additional tests status
    needs: generate_recommended_tests
    if: ${{ needs.generate_recommended_tests.outputs.run_acceptance_tests == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dummy Additional tests passed (skipped)"
