name: 'Suggested tests to cover this Pull Request'

on:
  pull_request_target:
    paths:
      - '**.java'

jobs:
  tests-covering-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm i ioredis

      - id: files
        uses: Ana06/get-changed-files@v2.3.0
        with:
          filter: '*.java'

      - id: tests_covering_pr
        name: Tests covering PR
        env:
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
        run: |
          echo "Running test coverage analysis..."
          echo "result=$(node .github/scripts/test_covering_pr.js ${{ steps.files.outputs.added_modified }})" >> $GITHUB_ENV

      - name: Write test results to PR comment
        uses: actions-cool/maintain-one-comment@v3
        with:
          body: |
            <!-- suggested_tests -->
            **Recommended Tests for this PR**  
            ```
            ${{ env.result }}
            ```
          body-include: '<!-- suggested_tests -->'
